#!/bin/bash

DIR=`dirname $0`
C32S="hdt menu sysdump"

cp -a /usr/share/hwdata/pci.ids $DIR
cp -a /lib/modules/`uname -r`/modules.pcimap $DIR

cp -a /usr/share/syslinux/pxelinux.0 $DIR
for i in $C32S; do
  cp -a /usr/share/syslinux/$i.c32 $DIR
done

rsync -avPH --inplace $DIR/* ftp:tftpboot/ \
  --exclude=rsync --exclude='**/.svn' \
  --exclude=kickstart \
  --exclude=config

cd kickstart
./rsync
cd ..
